openapi: 3.0.3
info:
  title: LearnEng API
  termsOfService: https://swagger.io/terms/
  contact:
    email: quannguyenminh1001@gmail.com
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: http://localhost/api/v1
tags:
  - name: auth
    description: Mọi thứ về xác thực người dùng
  - name: topic
    description: Chủ đề
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Đăng nhập
      description: Xử lý đăng nhập
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/AuthDTO'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthDTO'
        required: true
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginSuccess'
            application/xml:
              schema:
                $ref: '#/components/schemas/LoginSuccess'
        '401':
          description: Tài khoản hoặc mật khẩu không đúng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 401
                message: "Tài khoản hoặc mật khẩu không đúng"
        '500':
          description: Lỗi không xác định
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 500
                message: "Lỗi không xác định. Thử lại sau"
      security:
        - jwt_auth: [ ]
  /auth/register:
    post:
      tags:
        - auth
      summary: Đăng ký
      description: Xử lý đăng nhập
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/AuthDTO'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthDTO'
        required: true
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
            application/xml:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '400':
          description: Tên đăng nhập đã tồn tại
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 500
                message: "Tên đăng nhập đã tồn tại"
        '500':
          description: Lỗi không xác định
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 500
                message: "Lỗi không xác định. Thử lại sau"
      security:
        - jwt_auth: [ ]
  /topics:
    post:
      tags:
        - topic
      summary: Tạo Topic
      operationId: createTopic
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TopicDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/TopicDTO'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TopicDTO'
        required: true
      responses:
        '201':
          description: Thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Topic'
            application/xml:
              schema:
                $ref: '#/components/schemas/Topic'
        '400':
          description: Tên chủ đề đã tồn tại
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 400
                message: "Tên chủ đề đã tồn tại"
        '500':
          description: Lỗi không xác định
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 500
                message: "Lỗi không xác định. Thử lại sau"
      security:
        - jwt_auth: [ ]
    get:
      tags:
        - topic
      summary: Lấy thông tin chủ đề
      parameters:
        - name: name
          description: Tên chủ đề
          in: query
          schema:
            type: string
            example: family
        - name: type
          description: Kiểu chủ đề
          in: query
          schema:
            type: string
            enum:
              - THEORY
              - VOCABULARY
      operationId: getTopics
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topic'
            application/xml:
              schema:
                $ref: '#/components/schemas/Topic'
        '500':
          description: Lỗi không xác định
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 500
                message: "Lỗi không xác định. Thử lại sau"
      security:
        - jwt_auth: [ ]
  /topics/{id}:
    get:
      tags:
        - topic
      summary: Lấy thông tin chủ đề theo ID
      parameters:
        - name: id
          description: Topic ID
          in: path
          required: true
          schema:
            type: string
            example: 6694e9136fe1f7bae3db86fc
      operationId: getTopic
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Topic'
            application/xml:
              schema:
                $ref: '#/components/schemas/Topic'
        '404':
          description: Không tìm thấy đề mục
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 400
                message: "Không tìm thấy đề mục"
        '500':
          description: Lỗi không xác định
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 500
                message: "Lỗi không xác định. Thử lại sau"
      security:
        - jwt_auth: [ ]
    put:
      tags:
        - topic
      summary: Cập nhật thông tin chủ đề theo ID
      parameters:
        - name: id
          description: Topic ID
          in: path
          required: true
          schema:
            type: string
            example: 6694e9136fe1f7bae3db86fc
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TopicDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/TopicDTO'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TopicDTO'
        required: true
      operationId: updateTopic
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Topic'
            application/xml:
              schema:
                $ref: '#/components/schemas/Topic'
        '404':
          description: Không tìm thấy đề mục
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 400
                message: "Không tìm thấy đề mục"
        '500':
          description: Lỗi không xác định
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 500
                message: "Lỗi không xác định. Thử lại sau"
      security:
        - jwt_auth: [ ]
  /topics/{topicId}/vocabularies:
    get:
      tags:
        - topic
      summary: Lấy tất cả từ vựng của chủ đề
      parameters:
        - name: topicId
          description: Topic ID
          in: path
          required: true
          schema:
            type: string
            example: 6694e9136fe1f7bae3db86fc
      operationId: getVocabularies
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vocabulary'
            application/xml:
              schema:
                $ref: '#/components/schemas/Vocabulary'
        '404':
          description: Không tìm thấy chủ đề hoặc chủ đề không phải loại từ vựng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 400
                message: "Không tìm thấy chủ đề hoặc chủ đề không phải loại từ vựng"
        '500':
          description: Lỗi không xác định
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 500
                message: "Lỗi không xác định. Thử lại sau"
      security:
        - jwt_auth: [ ]
    post:
      tags:
        - topic
      summary: Thêm từ vựng cho chủ đề
      parameters:
        - name: topicId
          description: Topic ID
          in: path
          required: true
          schema:
            type: string
            example: 6694e9136fe1f7bae3db86fc
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VocabularyDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/VocabularyDTO'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VocabularyDTO'
        required: true
      operationId: createVocabulary
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vocabulary'
            application/xml:
              schema:
                $ref: '#/components/schemas/Vocabulary'
        '404':
          description: Không tìm thấy chủ đề hoặc chủ đề không phải loại từ vựng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 400
                message: "Không tìm thấy chủ đề hoặc chủ đề không phải loại từ vựng"
        '500':
          description: Lỗi không xác định
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 500
                message: "Lỗi không xác định. Thử lại sau"
      security:
        - jwt_auth: [ ]
  /topics/{topicId}/vocabularies/{vocabularyId}:
    put:
      tags:
        - topic
      summary: Cập nhật từ vựng
      parameters:
        - name: topicId
          description: Topic ID
          in: path
          required: true
          schema:
            type: string
            example: 6694e9136fe1f7bae3db86fc
        - name: vocabularyId
          description: Vocabulary ID
          in: path
          required: true
          schema:
            type: string
            example: 6694e9136fe1f7bae3db86fc
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VocabularyDTO'
          application/xml:
            schema:
              $ref: '#/components/schemas/VocabularyDTO'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VocabularyDTO'
        required: true
      operationId: updateVocabulary
      responses:
        '200':
          description: Thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vocabulary'
            application/xml:
              schema:
                $ref: '#/components/schemas/Vocabulary'
        '404':
          description: | 
            ** Mô tả **
            - Không tìm thấy chủ đề hoặc chủ đề không phải loại từ vựng
            - Không tìm thấy từ vựng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 400
                message: "Không tìm thấy chủ đề hoặc chủ đề không phải loại từ vựng"
        '500':
          description: Lỗi không xác định
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseError'
              example:
                timestamp: "2024-07-15T17:11:02.251Z"
                status: 500
                message: "Lỗi không xác định. Thử lại sau"
      security:
        - jwt_auth: [ ]
components:
  schemas:
    Vocabulary:
      type: object
      properties:
        _id:
          type: string
          example: "6696c21db49ccce616c5c3f6"
        topicId:
          type: string
          example: "6696accf6dee071c1bc7d18d"
        word:
          type: string
          example: "Friend"
        meaning:
          type: string
          example: "Bạn bè dữ chưa ?"
        example:
          type: string
          example: "He is my best friend"
        status:
          type: string
          enum: [ "ACTIVE", "DELETED", "INACTIVE" ]
          example: "ACTIVE"
        createdAt:
          type: string
          format: date-time
          example: "2024-07-16T18:55:25.238Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-07-16T19:09:21.402Z"
      required:
        - _id
        - topicId
        - word
        - meaning
        - status
        - createdAt
        - updatedAt
    VocabularyDTO:
      type: object
      properties:
        word:
          type: string
          example: "Friend"
        meaning:
          type: string
          example: "Bạn bè dữ chưa ?"
        example:
          type: string
          example: "He is my best friend"
    BaseError:
      type: object
      properties:
        timestamp:
          type: string
          example: 2024-07-15T17:11:02.251Z
        status:
          type: integer
          example: 404
        message:
          type: string
          example: Mô tả lỗi
      xml:
        name: baseError
    LoginSuccess:
      type: object
      properties:
        refreshToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTRmMDZkMDMxZjhiMzQxZmNkZGQ5OSIsInVzZXJuYW1lIjoibWluaHF1YW56ejEwMDIiLCJpYXQiOjE3MjEwNjI5NzksImV4cCI6MTcyMjI3MjU3OX0.w8182_4ltXLseWrj0CIdNmCPVSDFfjsTq_QBqne0EfQ
        accessToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTRmMDZkMDMxZjhiMzQxZmNkZGQ5OSIsInVzZXJuYW1lIjoibWluaHF1YW56ejEwMDIiLCJpYXQiOjE3MjEwNjI5NzksImV4cCI6MTcyMTA2NjU3OX0.JrUEbhJnUH-_BAAH6EsH0EWasv6wWYVWvkpgk9hMktU
        profile:
          $ref: '#/components/schemas/UserDTO'
      xml:
        name: loginSuccess
    AuthDTO:
      type: object
      properties:
        username:
          type: string
          example: minhquanzz1002
        password:
          type: string
          example: Minh123123@
      xml:
        name: authDTO
    UserDTO:
      type: object
      properties:
        _id:
          type: string
          example: 6694f06d031f8b341fcddd99
        name:
          type: string
          example: Nguyen Minh Quan
        username:
          type: string
          example: minhquanzz1002
        status:
          type: string
          example: ACTIVE
          enum:
            - ACTIVE
            - DELETED
            - INACTIVE
        createdAt:
          type: string
          example: 2024-07-15T09:48:29.678Z
          format: date
        updatedAt:
          type: string
          example: 2024-07-15T09:48:29.678Z
          format: date
      xml:
        name: userDTO
    Topic:
      type: object
      properties:
        _id:
          type: string
          example: "6694e9136fe1f7bae3db86fc"
        name:
          type: string
          example: "Chủ đề 2"
        description:
          type: string
          example: "Mô tả"
        type:
          type: string
          enum:
            - THEORY
            - VOCABULARY
        status:
          type: string
          enum:
            - ACTIVE
            - DELETED
            - INACTIVE
          example: "ACTIVE"
        createdAt:
          type: string
          format: date-time
          example: "2024-07-15T09:17:07.361Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-07-15T09:17:07.361Z"
      xml:
        name: topic
    TopicDTO:
      type: object
      properties:
        type:
          type: string
          enum:
            - THEORY
            - VOCABULARY
        name:
          type: string
          example: "Chủ đề 2"
        description:
          type: string
          example: "Mô tả"
      xml:
        name: topicDTO
  securitySchemes:
    jwt_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Nhập JWT của bạn vào đây